- name: Download Google Chrome .deb package
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome.deb
    mode: '0644'
  when: ansible_os_family == "Debian"
  
- name: Install Google Chrome from .deb package
  become: true
  apt:
    deb: /tmp/google-chrome.deb
    state: present
  when: ansible_os_family == "Debian"

- name: Remove Google Chrome .deb package
  file:
    path: /tmp/google-chrome.deb
    state: absent
  when: ansible_os_family == "Debian"