- name: Import Cloudflare GPG key (Fedora)
  become: true
  ansible.builtin.rpm_key:
    key: https://pkg.cloudflareclient.com/pubkey.gpg
    state: present

- name: Add Cloudflare WARP repository (Fedora)
  become: true
  ansible.builtin.get_url:
    url: https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
    dest: /etc/yum.repos.d/cloudflare-warp.repo
    mode: "0644"

- name: Install Cloudflare WARP (Fedora)
  become: true
  ansible.builtin.dnf:
    name: cloudflare-warp
    state: present
