---
# Remove conflicting container tools (optional but recommended)
- name: Remove conflicting container packages
  become: true
  community.general.pacman:
    name:
      - podman
      - buildah
      - containerd
    state: absent
  failed_when: false

# Install Docker

- name: Install Docker
  become: true
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present
    update_cache: true

# Enable and start Docker

- name: Enable and start Docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
