- name: Add Antigravity RPM repository
  become: true
  ansible.builtin.yum_repository:
    name: antigravity-rpm
    description: Antigravity RPM Repository
    baseurl: https://us-central1-yum.pkg.dev/projects/antigravity-auto-updater-dev/antigravity-rpm
    enabled: true
    gpgcheck: false
  when: ansible_facts.os_family == "RedHat"

- name: Install antigravity package (RPM)
  become: true
  ansible.builtin.dnf:
    name: antigravity
    state: present
  when: ansible_facts.os_family == "RedHat"
